name: multiseq
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - backcall=0.2.0
  - ca-certificates=2020.6.24
  - certifi=2020.6.20
  - decorator=4.4.2
  - ipykernel=5.3.4
  - ipython=7.16.1
  - ipython_genutils=0.2.0
  - jedi=0.17.1
  - jupyter_client=6.1.6
  - jupyter_core=4.6.3
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20191231
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libsodium=1.0.18
  - libstdcxx-ng=9.1.0
  - ncurses=6.2
  - openssl=1.1.1g
  - parso=0.7.0
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=20.1.1
  - prompt-toolkit=3.0.5
  - ptyprocess=0.6.0
  - pygments=2.6.1
  - python=3.8
  - python-dateutil=2.8.1
  - pyzmq=19.0.1
  - readline=8.0
  - setuptools=49.2.0
  - six=1.15.0
  - sqlite=3.32.3
  - tk=8.6.10
  - tornado=6.0.4
  - traitlets=4.3.3
  - wcwidth=0.2.5
  - wheel=0.34.2
  - xz=5.2.5
  - zeromq=4.3.2
  - zlib=1.2.11
  - pip:
    - anndata==0.7.4
    - argparse==1.4.0
    - bitvector==3.4.9
    - click==7.1.2
    - cycler==0.10.0
    - cython==0.29.21
    - docutils==0.16
    - fuzzywuzzy==0.18.0
    - get-version==2.1
    - gmm-demux==0.2.1.2
    - h5py==2.10.0
    - joblib==0.16.0
    - kiwisolver==1.2.0
    - legacy-api-wrap==1.2
    - leidenalg==0.8.1
    - llvmlite==0.33.0
    - matplotlib==3.3.0
    - natsort==7.0.1
    - networkx==2.4
    - numba==0.50.1
    - numexpr==2.7.1
    - numpy==1.19.1
    - numpy-groupies
    - packaging==20.4
    - pandas==1.1.0
    - patsy==0.5.1
    - pillow==7.2.0
    - pyparsing==2.4.7
    - python-igraph==0.8.2
    - pytz==2020.1
    - scanpy==1.5.1
    - scikit-learn==0.23.2
    - scikit-misc==0.1.3
    - scipy==1.5.2
    - seaborn==0.10.1
    - setuptools-scm==4.1.2
    - sklearn==0.0
    - sparse-dot-topn==0.2.9
    - statistics==1.0.3.5
    - statsmodels==0.11.1
    - tables==3.6.1
    - tabulate==0.8.7
    - texttable==1.6.2
    - threadpoolctl==2.1.0
    - tqdm==4.48.2
    - umap-learn==0.4.6

